# ===================================================================
# CONFIGURACIÓN BASE (PERFIL 'DEFAULT')
# ===================================================================
spring.cache.type: simple

spring:
  datasource:
    url: jdbc:h2:mem:navigator;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.H2Dialect

# Puerto por defecto para la aplicación
server:
  port: 8080

# Mensaje de bienvenida por defecto
mensaje:
  bienvenida: Hola desde el ambiente DEFAULT

# OpenAPI / Swagger UI Configuration
api:
  info:
    title: API de Navegación (Default)
    version: v1.0.0
    description: API para planificar rutas usando el perfil por defecto.
    contact:
      name: Equipo de Desarrollo
      email: default-support@tuempresa.com
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html

logging:
  level:
    org.springframework.cache: INFO
