spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/navigator
    driver-class-name: org.postgresql.Driver
    username: navigator
    password: changeMe
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: true
